Repository developer-student-club-thapar/officialWebsite, pull requests merged in 2020-05, with the labels that each got.

#68 Added slack button
  README.md
Labels: documentation, enhancement

#76 added webp images
  Frontend/src/assets/dsc_logo.webp
  Frontend/src/assets/header.webp
  Frontend/src/assets/project-planning-header@2x.webp
  Frontend/src/assets/slack.webp
  Frontend/src/pages/HomeAlt.js
Labels: frontend

#103 add lead endpoint
  backend/DSCBackend/__pycache__/urls.cpython-38.pyc
  backend/DSCBackend/__pycache__/views.cpython-38.pyc
  backend/DSCBackend/urls.py
  backend/DSCBackend/views.py
  backend/events/__pycache__/models.cpython-38.pyc
  backend/media/profile-images/WhatsApp_Image_2020-05-09_at_3.jpg
  backend/media/profile-images/buyerportalvsemail.jpg
  backend/media/profile-images/buyerportalvsemail_pZ9VaCU.jpg
  backend/team/__pycache__/serializers.cpython-38.pyc
  backend/team/__pycache__/urls.cpython-38.pyc
  backend/team/__pycache__/views.cpython-38.pyc
Labels: python

#134 Added auto-deployment
  .travis.yml
  package.json
Labels: enhancement

#141 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#149 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#154 [WIP] Changes in cards
  src/pages/Events.js
  src/pages/Project.js
Labels: enhancement, frontend
